### PR TITLE
Align popup list items & Hide unit/state descr. if not in createMode

### PR DESCRIPTION
**Pull request by florian-h05**

### CODE REVIEW

**Comment by florian-h05** [comment]
This is my preferred approach over adding another dependency to VueMultiselect, which honestly did not have the best start with Main UI.

**Comment by jimtng** [comment]
Agreed that vue-multiselect doesn't have a great start. I tried another component, and although it has no errors, it doesn't seem to work well in dark mode. So for now, I'll abandon the idea of using a drop down and revert to the smart-select.

Thanks for figuring out the css!

I'll see if I can revert all the other dropdowns too so they're all the same

**Comment by florian-h05** [comment]
IIRC group-form, semantics-picker are the only ones that introduced dropdowns.

**Comment by jimtng** [comment]
Do you want everything to revert back to smart-select?
Aggregation function?
Item type?

**Comment by florian-h05** [comment]
Dimension should be smart-select in any case.
For Item type and aggregation function, I am not sure - but consistency is always nice and TBH the dropdowns don't look that great. However do the dropdowns have the benefit, that you don't have to move your mouse too much on a large screen.
For visual consistency, I'd use the popover for type and aggregation and popup for dimension.

**Comment by florian-h05** [comment]
I have also found an issue with `setDimension` in item-form.vue

**Comment by jimtng** [comment]
> For visual consistency, I'd use the popover for type and aggregation and popup for dimension.

I tried popover, but I prefer popup for two reasons:
- popup allows searching, it's handy, even for selecting item type
- popover proves to be too narrow by default, it truncates some aggregation function (eg. on Switch).
So I've changed them all back to popup now.



> I have also found an issue with `setDimension` in item-form.vue

What's the issue?

**Comment by florian-h05** [comment]
> I tried popover, but I prefer popup for two reasons:

Fine, then let's continue to use popup.

> What's the issue?

See https://github.com/jimtng/openhab-webui/pull/4.

**Pull request merged**
